CREATE TABLE IF NOT EXISTS mods_buffer_skill (
  `skill_id` int(11) NOT NULL,
  `skill_level` int(11) NOT NULL,
  `skill_fee_id` int(11) NOT NULL DEFAULT '0',
  `skill_fee_amount` bigint(20) NOT NULL DEFAULT '0',
  `skill_comp` varchar(35) DEFAULT NULL,
  `skill_desc` longtext,
  `skill_icon` varchar(200) DEFAULT NULL,
  `skill_group` varchar(10) NOT NULL DEFAULT 'None',
  `skill_donator` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`skill_id`,`skill_level`)
);

INSERT IGNORE INTO mods_buffer_skill VALUES (271, 1, 57, 10000, '', 'Increases the P. Atk. of all party members by 12%. MP consumption is increased when dancing while song&dance effect lasts. Requires a dualsword weapon.', 'icon.skill0271', 'Dance', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (272, 1, 57, 10000, '', 'Increases the accuracy of all party members by 4. MP consumption is increased when dancing while song&dance effect lasts. Requires a dualsword weapon.', 'icon.skill0272', 'Dance', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (273, 1, 57, 10000, '', 'Increases the M. Atk. of all party members by 20%. MP consumption is increased when dancing while song&dance effect lasts. Requires a dualsword weapon.', 'icon.skill0273', 'Dance', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (274, 1, 57, 10000, '', 'Increases the critical attack power of all party members by 35%. MP consumption is increased when dancing while song&dance effect lasts. Requires a dualsword weapon.', 'icon.skill0274', 'Dance', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (275, 1, 57, 10000, '', 'Increases the Atk. Spd. of all party members by 15%. MP consumption is increased when dancing while song&dance effect lasts. Requires a dualsword weapon.', 'icon.skill0275', 'Dance', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (276, 1, 57, 10000, '', 'Decreases the magic-canceling damage of all party members by 40 and increases Casting Spd. by 30%. MP consumption is increased when dancing while song&dance effect lasts. Requires a dualsword weapon.', 'icon.skill0276', 'Dance', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (277, 1, 57, 10000, '', 'Increases the divine attribute P. Atk. of all party members by 20. MP consumption is increased when dancing while song&dance effect lasts. Requires a dualsword weapon.', 'icon.skill0277', 'Dance', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (307, 1, 57, 10000, '', 'Increases party members resistance to water attacks by 30. MP consumption is increased when dancing while song&dance effect lasts. Requires a dualsword weapon.', 'icon.skill0307', 'Dance', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (309, 1, 57, 10000, '', 'Increases party members resistance to earth attacks by 30. MP consumption is increased when dancing while song&dance effect lasts. Requires a dualsword weapon.', 'icon.skill0309', 'Dance', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (310, 1, 57, 10000, '', 'Gives all party members the ability to recover as HP 8% of any standard short-range physical damage inflicted on the enemy. MP consumption is increased when dancing while song&dance effect lasts. Requires a dualsword weapon.', 'icon.skill0310', 'Dance', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (311, 1, 57, 10000, '', 'Gives all party members the ability to decrease by 30 any environment-related damage received. Increases MP consumption when dancing while song&dance effect lasts. Requires a dualsword weapon.', 'icon.skill0311', 'Dance', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (365, 1, 57, 10000, '', 'Increases all party members damage magic critical attack rate by 100%. Also increases MP consumption when dancing while song&dance effect lasts. Requires a dualsword weapon.', 'icon.skill0365', 'Dance', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (366, 1, 57, 10000, '', 'Decreases all party members movement speed by 50% and prevents them from being pre-emptively attacked by monsters. Also increases MP consumption when dancing while song&dance effect lasts. Requires a dualsword weapon.', 'icon.skill0366', 'Dance', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (530, 1, 57, 10000, '', 'Increases all party members resistance to divine or Dark attacks by 30. Also increases MP consumption when dancing while song&dance effect lasts. Requires a dualsword weapon.', 'icon.skill0530', 'Dance', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (915, 1, 57, 10000, '', 'Decreases a party members P. Def., M. Def. and evasion, and increases their P. Atk., M. Atk., Atk. Spd., Casting Spd. and movement speed.', 'icon.skill0915', 'Dance', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1059, 3, 57, 10000, '', 'Increases M. Atk. by 75%.', 'icon.skill1059', 'Elder', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1087, 3, 57, 10000, '', 'Increases evasion by 4.', 'icon.skill1087', 'Elder', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1257, 3, 57, 10000, '', 'Increases the weight penalty interval by 9000.', 'icon.skill1257', 'Elder', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1259, 4, 57, 10000, '', 'Increases resistance to stun attacks by 40%.', 'icon.skill1259', 'Elder', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1268, 4, 57, 10000, '', '9% of the standard short-range physical damage inflicted on the enemy is recovered as HP.', 'icon.skill1268', 'Elder', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1303, 2, 57, 10000, '', 'Increases by 2 the damage rate of magic.', 'icon.skill1303', 'Elder', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1353, 1, 57, 10000, '', 'Increases resistance to Dark attacks by 30 and resistance to divine attacks by 20.', 'icon.skill1353', 'Elder', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1354, 1, 57, 10000, '', 'Increases resistance to buff-canceling attacks by 30 and resistance to de-buff attacks by 20.', 'icon.skill1354', 'Elder', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1355, 1, 57, 10000, '', 'A powerful spirit acts to increase the damage caused by the targeted party members damage magic by 2, MP recovery bonus by 20%, P. Atk. by 10%, P. Def. by 20%, Atk. Spd. by 20%, M. Atk. by 20%, M. Def. by 20%, Casting Spd. by 20%, and resistance to de-buffs by 10%. Decreases movement speed by 20% and MP consumption for skill use by 5%. Consumes 10 Spirit Ores.', 'icon.skill1355', 'Elder', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1357, 1, 57, 10000, '', 'A powerful spirit acts to increase a party members Max HP by 20%, rate of critical attack by 20%, damage magic critical attack rate by 20%, P. Atk. by 10%, P. Def. by 20%, Atk. Spd. by 20%, M. Atk. by 20%, M. Def. by 20%, Casting Spd. by 20%, and resistance to de-buff by 10%. Decreases movement speed by 20%. Bestows the ability to recover as HP 5% of the standard short-range physical damage inflicted on the enemy. Consumes 10 Spirit Ores.', 'icon.skill1357', 'Elder', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1397, 3, 57, 10000, '', 'Decreases physical skill MP consumption by 20%, magic skill MP consumption by 10%, and song&dance skill MP consumption by 20%. Consumes 3 Spirit Ores.', 'icon.skill1397', 'Elder', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1460, 1, 57, 10000, '', 'increases the recharge power received by the target by 85.', 'icon.skill1460', 'Elder', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1499, 1, 57, 10000, '', 'Combines P. Atk. increase and P. Def. increase to have more advanced combat power increase effect. Increases P. Atk. by 15% and P. Def. by 15%.', 'icon.skill1499', 'Improved', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1500, 1, 57, 10000, '', 'Combines magic power increase and magic resistance increase to have more advanced magic ability increase effect. Increases M. Atk. by 75% and M. Def. by 30%.', 'icon.skill1500', 'Improved', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1501, 1, 57, 10000, '', 'Combines maximum HP increase and maximum MP increase to have more advanced mental and physical power. Increases Max HP by 35% and Max MP by 35%.', 'icon.skill1501', 'Improved', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1502, 1, 57, 10000, '', 'Combines critical rate increase and critical power increase to have more advanced critical increase effect. Increases critical rate by 30% and critical power by 35%.', 'icon.skill1502', 'Improved', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1503, 1, 57, 10000, '', 'Combines shield Def. rate increase and shield P. Def. increase to have more advanced shield ability increase effect. Increases shield defense rate by 30% and shield P. Def. by 50%.', 'icon.skill1503', 'Improved', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1504, 1, 57, 10000, '', 'Combines Spd. increase and Evasion increase to have more advanced movement increase effect. Increases moving speed by 33 and evasion by 4.', 'icon.skill1504', 'Improved', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (499, 3, 57, 10000, '', 'Increases resistance to altered state mind attacks by 100.', 'icon.skill0499', 'Kamael', 2);
INSERT IGNORE INTO mods_buffer_skill VALUES (1470, 1, 57, 10000, '', 'Increases the M. Def. of all party members by 3000 for 30 seconds.', 'icon.skill1470', 'Kamael', 2);
INSERT IGNORE INTO mods_buffer_skill VALUES (1476, 3, 57, 10000, '', 'Awakens a party members destructive instincts and increases P. Atk., critical attack rate and critical damage by 50%.', 'icon.skill1476', 'Kamael', 2);
INSERT IGNORE INTO mods_buffer_skill VALUES (1477, 3, 57, 10000, '', 'Stirs up the bloodsucking urge and gives all party members the ability to recover as HP 80% of the standard short-range physical damage inflicted on the enemy.', 'icon.skill1477', 'Kamael', 2);
INSERT IGNORE INTO mods_buffer_skill VALUES (1478, 2, 57, 10000, '', 'Stirs up the defense instinct to increase M. Atk. by 1800 and M. Def. by 1350 for 15 seconds.', 'icon.skill1478', 'Kamael', 2);
INSERT IGNORE INTO mods_buffer_skill VALUES (1479, 3, 57, 10000, '', 'Stirs up the magic urge to increase M. Atk. by 95%, Casting Spd. by 15%, and the rate of Prominent Damage occurring with damage magic by 300% for 15 seconds.', 'icon.skill1479', 'Kamael', 2);
INSERT IGNORE INTO mods_buffer_skill VALUES (1003, 3, 57, 10000, '', 'Increases the P. Atk. of nearby clan members by 15%.', 'icon.skill1003', 'Overlord', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1004, 3, 57, 10000, '', 'Increases the Casting Spd. of nearby clan members by 30%.', 'icon.skill1004', 'Overlord', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1005, 3, 57, 10000, '', 'Increases the P. Def. of nearby clan members by 15%.', 'icon.skill1005', 'Overlord', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1008, 3, 57, 10000, '', 'Increases the M. Def. of nearby clan members by 30%.', 'icon.skill1008', 'Overlord', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1249, 3, 57, 10000, '', 'Increases the accuracy of nearby clan members by 4.', 'icon.skill1249', 'Overlord', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1250, 3, 57, 10000, '', 'Increases the shield defense rate of nearby clan members by 50%. Effect 1.', 'icon.skill1250', 'Overlord', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1260, 3, 57, 10000, '', 'Increases the evasion of nearby clan members by 4.', 'icon.skill1260', 'Overlord', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1261, 2, 57, 10000, '', 'Decreases nearby clan members P. Def. by 8%, M. Def. by 16%, and evasion by 4, and increases P. Atk. by 8%, M. Atk. by 16%, Atk. Spd. by 8%, Casting Spd. by 8%, and moving speed by 8.', 'icon.skill1261', 'Overlord', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1282, 2, 57, 10000, '', 'Increases the movement speed of nearby clan members by 33.', 'icon.skill1282', 'Overlord', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1364, 1, 57, 10000, '', 'Increases nearby clan members accuracy by 4 and decreases the rate of being hit by a critical attack by 30%.', 'icon.skill1364', 'Overlord', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1365, 1, 57, 10000, '', 'Increases nearby clan members M. Atk. by 75% and M. Def. by 30%.', 'icon.skill1365', 'Overlord', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1414, 1, 57, 10000, '', 'A powerful spirit acts to increase Max CP of nearby clan members by 20%, CP recovery bonus by 20%, Max MP by 20%, critical attack rate by 20%, the power of Prominent Damage through damage magic by 20%, P. Atk. by 10%, P. Def. by 20%, Atk. Spd. by 20%, M. Atk. by 20%, M. Def. by 20%, Casting Spd. by 20%, and resistance to de-buff by 10%. Decreases movement speed by 20%. Consumes 40 Spirit Ores.', 'icon.skill1414', 'Overlord', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1415, 1, 57, 10000, '', 'Increases nearby clan members resistance to buff-canceling attacks by 30% and resistance to de-buff attacks by 20%.', 'icon.skill1415', 'Overlord', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1416, 1, 57, 10000, '', 'Regenerates nearby clan members CP by 800 and increases Max CP by 800. Consumes 20 Spirit Ores.', 'icon.skill1416', 'Overlord', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1536, 1, 57, 10000, '', 'Combines a party&clan members P. Atk. increase and P. Def. increase to have more advanced combat power increase effect. Increases P. Atk. by 15% and P. Def. by 15%.', 'icon.skill1536', 'Overlord', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1537, 1, 57, 10000, '', 'Combines a party&clan members critical rate increase and critical power increase effects for a more advanced critical increase effect. Increases critical rate by 30% and critical power by 35%.', 'icon.skill1537', 'Overlord', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1538, 1, 57, 10000, '', 'Combines a party&clan members maximum HP increase and maximum MP increase effects for more advanced mental and physical power. Increases Max HP by 35% and Max MP by 35%.', 'icon.skill1538', 'Overlord', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1032, 3, 57, 10000, '', 'Increases resistance to bleed attacks by 50%.', 'icon.skill1032', 'Prophet', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1033, 3, 57, 10000, '', 'Increases resistance to poison attacks by 50%.', 'icon.skill1033', 'Prophet', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1035, 4, 57, 10000, '', 'Increases resistance to hold, sleep and mental attacks by 50.', 'icon.skill1035', 'Prophet', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1036, 2, 57, 10000, '', 'Increases M. Def. by 30%.', 'icon.skill1036', 'Prophet', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1040, 3, 57, 10000, '', 'Increases P. Def. by 15%.', 'icon.skill1040', 'Prophet', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1043, 1, 57, 10000, '', 'Increases a party members divine attribute P. Atk. by 20.', 'icon.skill1043', 'Prophet', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1044, 3, 57, 10000, '', 'Increases HP Regeneration by 20%.', 'icon.skill1044', 'Prophet', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1045, 6, 57, 10000, '', 'Increases Max HP by 35%.', 'icon.skill1045', 'Prophet', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1048, 6, 57, 10000, '', 'Increases Max MP by 35%.', 'icon.skill1048', 'Prophet', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1062, 2, 57, 10000, '', 'Decreases a party members P. Def. by 8%, M. Def. by 16% and evasion by 4, and increases P. Atk. by 8%, M. Atk. by 16%, Atk. Spd. by 8%, Casting Spd. by 8%, and movement speed by 8.', 'icon.skill1062', 'Prophet', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1068, 3, 57, 10000, '', 'Increases P. Atk. by 15%.', 'icon.skill1068', 'Prophet', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1073, 2, 57, 10000, '', 'Increases lung capacity by 600%.', 'icon.skill1073', 'Prophet', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1077, 3, 57, 10000, '', 'Increases critical attack rate by 30%.', 'icon.skill1077', 'Prophet', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1078, 6, 57, 10000, '', 'Decreases magic cancel damage by 53.', 'icon.skill1078', 'Prophet', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1085, 3, 57, 10000, '', 'Increases Casting Spd. by 30%.', 'icon.skill1085', 'Prophet', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1086, 2, 57, 10000, '', 'Increases Atk. Spd. by 33%.', 'icon.skill1086', 'Prophet', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1182, 3, 57, 10000, '', 'Increases resistance to water attacks by 20.', 'icon.skill1182', 'Prophet', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1189, 3, 57, 10000, '', 'Increases resistance to wind attacks by 20.', 'icon.skill1189', 'Prophet', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1191, 3, 57, 10000, '', 'Increases resistance to fire attacks by 20.', 'icon.skill1191', 'Prophet', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1204, 2, 57, 10000, '', 'Increases movement speed by 33.', 'icon.skill1204', 'Prophet', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1240, 3, 57, 10000, '', 'Increases accuracy by 4.', 'icon.skill1240', 'Prophet', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1242, 3, 57, 10000, '', 'Increases critical attack power by 35%.', 'icon.skill1242', 'Prophet', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1243, 6, 57, 10000, '', 'Increases shield defense rate by 30%.', 'icon.skill1243', 'Prophet', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1304, 3, 57, 10000, '', 'Increases shield P. Def. by 50%.', 'icon.skill1304', 'Prophet', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1307, 3, 57, 10000, '', 'Increases the power of HP recovery magic received by all party members by 12%.', 'icon.skill1307', 'Prophet', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1311, 6, 57, 10000, '', 'Restores HP of all party members by 35% and increases Max HP by 35%.', 'icon.skill1311', 'Prophet', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1352, 1, 57, 10000, '', 'Increases resistance to fire, water, wind and earth attacks.', 'icon.skill1352', 'Prophet', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1356, 1, 57, 10000, '', 'A powerful spirit acts to increase a party members Max MP by 20%, HP recovery bonus by 20%, damage magic critical attack rate by 2, the power of critical attacks by 20%, P. Atk. by 10%, P. Def. by 20%, Atk. Spd. by 20%, M. Atk. by 20%, M. Def. by 20%, Casting Spd. by 20%, and resistance to de-buffs by 10%. Decreases movement speed by 20%. Consumes 10 Spirit Ores.', 'icon.skill1356', 'Prophet', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1388, 3, 57, 10000, '', 'Increases P. Atk. by 10%. Consumes 3 Spirit Ores.', 'icon.skill1388', 'Prophet', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1389, 3, 57, 10000, '', 'Increases P. Def. by 15%. Consumes 3 Spirit Ores.', 'icon.skill1389', 'Prophet', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1392, 3, 57, 10000, '', 'Increases resistance to divine attacks by 30.', 'icon.skill1392', 'Prophet', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1393, 3, 57, 10000, '', 'Increases resistance to Dark attacks by 30.', 'icon.skill1393', 'Prophet', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1542, 1, 57, 10000, '', 'Increases the targets P. Def. against Critical by 30%. When the target receives an attack above a certain amount of damage, the critical damage of General Short-Range Physical Attack is increased for 8 seconds.', 'icon.skill1542', 'Prophet', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (264, 1, 57, 10000, '', 'Increases the P. Def. of all party members by 25%. MP consumption is increased when singing while song&dance effect lasts.', 'icon.skill0264', 'Song', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (265, 1, 57, 10000, '', 'Increases HP Regeneration of all party members by 20%. MP consumption is increased when singing while song&dance effect lasts.', 'icon.skill0265', 'Song', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (266, 1, 57, 10000, '', 'Increases the evasion of all party members by 3. MP consumption is increased when singing while song&dance effect lasts.', 'icon.skill0266', 'Song', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (267, 1, 57, 10000, '', 'Increases the M. Def. of all party members by 30%. MP consumption is increased when singing while song&dance effect lasts.', 'icon.skill0267', 'Song', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (268, 1, 57, 10000, '', 'Increases the movement speed of all party members by 20. MP consumption is increased when singing while song&dance effect lasts.', 'icon.skill0268', 'Song', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (269, 1, 57, 10000, '', 'Increases the critical attack rate of all party members by 100%. MP consumption is increased when singing while song&dance effect lasts.', 'icon.skill0269', 'Song', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (270, 1, 57, 10000, '', 'Increases the resistance of all party members to Dark attacks by 20. MP consumption is increased when singing while song&dance effect lasts.', 'icon.skill0270', 'Song', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (304, 1, 57, 10000, '', 'Increases Max HP of all party members by 30%. Also increases MP consumption when singing while sing&dance effect lasts.', 'icon.skill0304', 'Song', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (305, 1, 57, 10000, '', 'Gives a party member the ability to transfer 20% of received standard short-range damage back to the enemy. Also increases MP consumption when singing while sing&dance effect lasts.', 'icon.skill0305', 'Song', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (306, 1, 57, 10000, '', 'Increases party members resistance to fire attacks by 30. Increases MP consumption when singing while sing&dance effect lasts.', 'icon.skill0306', 'Song', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (308, 1, 57, 10000, '', 'Increases party members resistance to wind attacks by 30. Increases MP consumption when singing while sing&dance effect lasts.', 'icon.skill0308', 'Song', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (349, 1, 57, 10000, '', 'Decreases all party members physical&magic skill MP consumption by 5% and re-use time by 20%. Also increases MP consumption when singing while sing&dance effect lasts.', 'icon.skill0349', 'Song', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (363, 1, 57, 10000, '', 'Increases all party members MP recovery bonus by 20%, and decreases magic skill use MP consumption by 10%. Also increases MP consumption when singing while sing&dance effect lasts.', 'icon.skill0363', 'Song', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (364, 1, 57, 10000, '', 'Decreases all party members physical skill use and song&dance skill use MP consumption by 20% and physical skill and song&dance skill reuse time by 10%. Increases the additional MP consumption when singing while sing&dance effect lasts.', 'icon.skill0364', 'Song', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (529, 1, 57, 10000, '', 'Increases all party members resistance to fire, water, wind and earth attacks by 30. Also increases MP consumption when singing while sing&dance effect lasts.', 'icon.skill0529', 'Song', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (764, 1, 57, 10000, '', 'Increases a party members tolerance to bows by 30. Increases the additional MP consumption when singing while sing&dance effect lasts.', 'icon.skill0764', 'Song', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1323, 1, 57, 10000, '', 'Maintains targets buff&de-buff condition even following death and resurrection. The Blessing of Noblesse and the Amulet of Luck disappear, however. Consumes 5 Spirit Ores.', 'icon.skill1323', 'Special', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1182, 320, 57, 10000, '+20 Power', 'Increases the effectiveness by 4.<br1>Increases resistance to water attacks by 106. Enchant Power: Increases effectiveness.', 'icon.skill1182', 'Special', 1);
INSERT IGNORE INTO mods_buffer_skill VALUES (1189, 320, 57, 10000, '+20 Power', 'Increases effectiveness by 4.<br1>Increases resistance to wind attacks by 106. Enchant Power: Increases effectiveness.', 'icon.skill1189', 'Special', 1);
INSERT IGNORE INTO mods_buffer_skill VALUES (1191, 321, 57, 10000, '+21 Power', 'Increases effectiveness by 5.<br1>Increases resistance to fire attacks by 111. Enchant Power: Increases effectiveness.', 'icon.skill1191', 'Special', 1);
INSERT IGNORE INTO mods_buffer_skill VALUES (1363, 315, 57, 10000, '+15 Decrease Penalty', 'Movement speed consumption penalty decreases by 1%.<br1>Restores 20% of all party members HP. A powerful spirit acts to increase a party members Max HP by 20%, damage magic critical attack power by 2, critical attack power by 20%, P. Atk. by 10%, P. Def. by 20%, Atk. Spd. by 20%, M. Atk. by 20%, M. Def. by 20%, Casting Spd. by 20%, resistance to de-buffs by 10%, and accuracy by 4. Consumes 40 Spirit Ores. Enchant Decrease Penalty: Movement speed consumption penalty decreases.', 'icon.skill1363', 'Special', 1);
INSERT IGNORE INTO mods_buffer_skill VALUES (1392, 120, 57, 10000, '+20 Power', 'Increases divine resistance by 4.<br1>Increases resistance to divine attacks by 110. Enchant Power: Increases divine resistance.', 'icon.skill1392', 'Special', 1);
INSERT IGNORE INTO mods_buffer_skill VALUES (1393, 120, 57, 10000, '+20 Power', 'Increases Dark resistance by 4.<br1>Increases resistance to Dark attacks by 110. Enchant Power: Power of the skill is increased.', 'icon.skill1393', 'Special', 1);
INSERT IGNORE INTO mods_buffer_skill VALUES (76, 1, 57, 10000, '', 'Possessed by a Bears soul, users P. Atk. and critical attack power are increased by 20% and movement speed is decreased by 30%. Requires a hand-to-hand weapon.', 'icon.skill0076', 'Special', 2);
INSERT IGNORE INTO mods_buffer_skill VALUES (83, 1, 57, 10000, '', 'Possessed by a Wolfs soul, users movement speed is increased by 20% and accuracy increased by 3. Requires a hand-to-hand weapon.', 'icon.skill0083', 'Special', 2);
INSERT IGNORE INTO mods_buffer_skill VALUES (109, 1, 57, 10000, '', 'Becomes possessed by an Ogres soul. Increases ones own P. Atk.&P. Def.&M. Def. by 30% and Critical Damage by 10%. Requires a hand-to-hand combat weapon to be equipped.', 'icon.skill0109', 'Special', 2);
INSERT IGNORE INTO mods_buffer_skill VALUES (282, 1, 57, 10000, '', 'User becomes possessed by a Pumas soul. Increases users accuracy by 6 and Atk. Spd. by 20%. Requires a hand-to-hand weapon.', 'icon.skill0282', 'Special', 2);
INSERT IGNORE INTO mods_buffer_skill VALUES (292, 1, 57, 10000, '', 'User is possessed by a Bisons soul, increasing accuracy when using a hand-to-hand weapon and increasing P. Atk. by 10% and the probability of critical attack by 100 when HP is below 60%. If HP is below 30%, P. Atk. is increased by 30% and critical attack rate is increased by 300. Requires a hand-to-hand weapon.', 'icon.skill0292', 'Special', 2);
INSERT IGNORE INTO mods_buffer_skill VALUES (298, 1, 57, 10000, '', 'Becomes possessed by a Rabbits soul. Increases ones own Atk. Spd. by 30%, moving speed by 30%, and evasion by 12. Requires a hand-to-hand combat weapon to be equipped.', 'icon.skill0298', 'Special', 2);
INSERT IGNORE INTO mods_buffer_skill VALUES (341, 1, 57, 10000, '', 'Gives a holy blessing by sacrificing oneself. Restores HP by 50%, and, increases resistance to buff cancel attacks by 100%, resistance to de-buff attacks by 30%, and the power of received HP recovery magic by 30%. Restores 50 HP every second.', 'icon.skill0341', 'Special', 2);
INSERT IGNORE INTO mods_buffer_skill VALUES (425, 1, 57, 10000, '', 'Becomes possessed by a Hawks soul. when using a hand-to-hand combat weapon, increases ones own accuracy by 6, critical attack rate by 100, and critical damage by 30%. Requires a hand-to-hand combat weapon to be equipped.', 'icon.skill0425', 'Special', 2);
INSERT IGNORE INTO mods_buffer_skill VALUES (1457, 1, 57, 10000, '', 'increases users magic MP consumption by 35% and M. Atk. by 25%.', 'icon.skill1457', 'Special', 2);
INSERT IGNORE INTO mods_buffer_skill VALUES (4701, 13, 57, 10000, '', 'Has a chance to remove curses that decrease Accuracy, P. Atk. and Atk. Spd. from all party members .', 'icon.skill1331', 'Special', 2);
INSERT IGNORE INTO mods_buffer_skill VALUES (4699, 13, 57, 10000, '', 'Queens buff magic Temporarily increases your party members critical damage amount rate and power. Effect 3.', 'icon.skill1331', 'Summon', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (4700, 13, 57, 10000, '', 'Queens buff magic temporarily increases party members P. Atk. and Accuracy. Effect 3.', 'icon.skill1331', 'Summon', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (4702, 13, 57, 10000, '', 'Buff magic used by the Unicorn Seraphim. Party members MP regeneration bonus temporarily increased. Effect 3.', 'icon.skill1332', 'Summon', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (4703, 13, 57, 10000, '', 'Unicorn Seraphims buff magic temporarily reduces party members magic skill recovery time. Effect 3.', 'icon.skill1332', 'Summon', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1002, 3, 57, 10000, '', 'Increases Casting Spd. of all party members by 30%.', 'icon.skill1002', 'Warcryer', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1006, 3, 57, 10000, '', 'Increases the M. Def. of all party members by 30%.', 'icon.skill1006', 'Warcryer', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1007, 3, 57, 10000, '', 'Increases the P. Atk. of all party members by 15%.', 'icon.skill1007', 'Warcryer', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1009, 3, 57, 10000, '', 'Increases the P. Def. of all party members by 15%.', 'icon.skill1009', 'Warcryer', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1229, 18, 57, 10000, '', 'Recovers 58 HP per second for all party members for 15 seconds.', 'icon.skill1229', 'Warcryer', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1251, 2, 57, 10000, '', 'Increases the Atk. Spd. of all party members by 33%.', 'icon.skill1251', 'Warcryer', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1252, 3, 57, 10000, '', 'Increases the evasion of all party members by 4.', 'icon.skill1252', 'Warcryer', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1253, 3, 57, 10000, '', 'Increases the critical attack power of all party members by 35%.', 'icon.skill1253', 'Warcryer', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1284, 3, 57, 10000, '', 'Gives a party member the ability to transfer 20% of received standard short-range damage back to the enemy.', 'icon.skill1284', 'Warcryer', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1308, 3, 57, 10000, '', 'Increases the critical attack rate of all party members by 30%.', 'icon.skill1308', 'Warcryer', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1309, 3, 57, 10000, '', 'Increases the accuracy of all party members by 4.', 'icon.skill1309', 'Warcryer', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1310, 4, 57, 10000, '', 'Gives all party members the ability to recover as HP 9% of any standard short-range physical damage inflicted on the enemy.', 'icon.skill1310', 'Warcryer', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1362, 1, 57, 10000, '', 'Increases all party members resistance to buff-canceling attacks by 30 and resistance to de-buff attacks by 20.', 'icon.skill1362', 'Warcryer', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1363, 1, 57, 10000, '', 'Recovers all party members HP by 20%, receives help from a great spirit to increase Max HP by 20%, damage magic critical attack power by 2, critical attack power by 20%, P. Atk. by 10%, P. Def. by 20%, Atk. Spd. by 20%, M. Atk. by 20%, M. Def. by 20%, Casting Spd. by 20%, resistance to de-buffs by 10%, and accuracy by 4. Decreases movement speed by 20%. Consumes 40 Spirit Ores.', 'icon.skill1363', 'Warcryer', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1413, 1, 57, 10000, '', 'A powerful spirit acts to increase Max MP of all party members by 15%, MP recovery bonus by 1.5 when wearing light or heavy armor, MP recovery bonus by 4 when wearing a robe, M. Def. by 30%, M. Atk. by 30%, Casting Spd. by 20%, resistance to fire, water, wind and earth damage by 10, resistance to de-buff attacks by 25, and resistance to buff-canceling attacks by 40. Consumes 40 Spirit Ores.', 'icon.skill1413', 'Warcryer', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1461, 1, 57, 10000, '', 'Decreases the critical damage received by a party member by 30%.', 'icon.skill1461', 'Warcryer', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (1519, 1, 57, 10000, '', 'Combines party members general attack damage absorption and Atk. Spd. increase to have a more advanced blood awakening effect. Increases Atk. Spd. by 33% and bestows the ability to recover as HP 9% of the standard short-range physical damage inflicted on the enemy.', 'icon.skill1519', 'Warcryer', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (825, 1, 57, 10000, '', 'Sharpens a bladed weapon to increase P. Atk. by 5% and critical rate by 20%.', 'icon.skill0825', 'Warsmith', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (826, 1, 57, 10000, '', 'Adds a spike to a blunt weapon to increase P. Atk. by 5% and its weight for shock attack by 8%.', 'icon.skill0826', 'Warsmith', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (827, 1, 57, 10000, '', 'Enhances the string of a bow or crossbow to increase P. Atk. by 5% and range by 100.', 'icon.skill0827', 'Warsmith', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (828, 1, 57, 10000, '', 'Enhances the armor surface to increase P. Def. by 10%.', 'icon.skill0828', 'Warsmith', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (829, 1, 57, 10000, '', 'Tans armor to increase P. Def. by 5% and evasion by 2. Works only on light armor users and cant be used on pets.', 'icon.skill0829', 'Warsmith', 0);
INSERT IGNORE INTO mods_buffer_skill VALUES (830, 1, 57, 10000, '', 'Embroiders a robe to increase P. Def. by 5% and MP recovery speed by 2.', 'icon.skill0830', 'Warsmith', 0);

CREATE TABLE IF NOT EXISTS mods_buffer_scheme (
  scheme_id INT NOT NULL AUTO_INCREMENT,
  player_id INT NOT NULL DEFAULT 0,
  scheme_name VARCHAR(25) NULL,
  scheme_type INT NOT NULL DEFAULT 0, -- 0 = Character 1 = Pet/Summon
  PRIMARY KEY(scheme_id)
);

INSERT IGNORE INTO mods_buffer_scheme VALUES (1, 0, 'Dagger', 0);
INSERT IGNORE INTO mods_buffer_scheme VALUES (2, 0, 'Archer', 0);
INSERT IGNORE INTO mods_buffer_scheme VALUES (3, 0, 'Warrior', 0);
INSERT IGNORE INTO mods_buffer_scheme VALUES (4, 0, 'Tanker', 0);
INSERT IGNORE INTO mods_buffer_scheme VALUES (5, 0, 'Healer', 0);
INSERT IGNORE INTO mods_buffer_scheme VALUES (6, 0, 'Mago', 0);
INSERT IGNORE INTO mods_buffer_scheme VALUES (7, 0, 'Fight', 1);
INSERT IGNORE INTO mods_buffer_scheme VALUES (8, 0, 'Defense', 1);
INSERT IGNORE INTO mods_buffer_scheme VALUES (9, 0, 'Mage', 1);

CREATE TABLE IF NOT EXISTS mods_buffer_content (
  skill_level INT NOT NULL,
  skill_id INT NOT NULL,
  scheme_id INT NOT NULL,
  PRIMARY KEY(skill_level, skill_id, scheme_id),
  FOREIGN KEY(skill_id, skill_level)
    REFERENCES mods_buffer_skill(skill_id, skill_level)
      ON DELETE CASCADE
      ON UPDATE CASCADE,
  FOREIGN KEY(scheme_id)
    REFERENCES mods_buffer_scheme(scheme_id)
      ON DELETE CASCADE
      ON UPDATE CASCADE
);

INSERT IGNORE INTO mods_buffer_content VALUES (1, 264, 1);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 265, 1);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 266, 1);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 267, 1);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 268, 1);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 269, 1);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 271, 1);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 272, 1);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 274, 1);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 275, 1);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 304, 1);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 349, 1);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 364, 1);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 764, 1);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 829, 1);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1323, 1);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1352, 1);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1362, 1);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1363, 1);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1416, 1);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1461, 1);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1499, 1);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1501, 1);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1502, 1);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1504, 1);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1542, 1);
INSERT IGNORE INTO mods_buffer_content VALUES (2, 1036, 1);
INSERT IGNORE INTO mods_buffer_content VALUES (2, 1062, 1);
INSERT IGNORE INTO mods_buffer_content VALUES (2, 1086, 1);
INSERT IGNORE INTO mods_buffer_content VALUES (3, 1044, 1);
INSERT IGNORE INTO mods_buffer_content VALUES (3, 1240, 1);
INSERT IGNORE INTO mods_buffer_content VALUES (3, 1388, 1);
INSERT IGNORE INTO mods_buffer_content VALUES (3, 1397, 1);
INSERT IGNORE INTO mods_buffer_content VALUES (4, 1035, 1);
INSERT IGNORE INTO mods_buffer_content VALUES (4, 1259, 1);
INSERT IGNORE INTO mods_buffer_content VALUES (4, 1268, 1);
INSERT IGNORE INTO mods_buffer_content VALUES (13, 4699, 1);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 264, 2);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 265, 2);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 267, 2);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 268, 2);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 269, 2);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 271, 2);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 272, 2);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 274, 2);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 275, 2);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 304, 2);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 349, 2);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 364, 2);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 764, 2);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 827, 2);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 829, 2);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 915, 2);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1323, 2);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1352, 2);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1362, 2);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1363, 2);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1416, 2);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1461, 2);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1499, 2);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1501, 2);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1502, 2);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1504, 2);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1542, 2);
INSERT IGNORE INTO mods_buffer_content VALUES (2, 1036, 2);
INSERT IGNORE INTO mods_buffer_content VALUES (2, 1062, 2);
INSERT IGNORE INTO mods_buffer_content VALUES (2, 1086, 2);
INSERT IGNORE INTO mods_buffer_content VALUES (3, 1044, 2);
INSERT IGNORE INTO mods_buffer_content VALUES (3, 1240, 2);
INSERT IGNORE INTO mods_buffer_content VALUES (3, 1388, 2);
INSERT IGNORE INTO mods_buffer_content VALUES (3, 1397, 2);
INSERT IGNORE INTO mods_buffer_content VALUES (4, 1035, 2);
INSERT IGNORE INTO mods_buffer_content VALUES (4, 1259, 2);
INSERT IGNORE INTO mods_buffer_content VALUES (13, 4699, 2);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 264, 3);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 265, 3);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 267, 3);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 268, 3);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 269, 3);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 271, 3);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 272, 3);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 274, 3);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 275, 3);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 304, 3);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 349, 3);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 364, 3);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 764, 3);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 829, 3);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 915, 3);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1323, 3);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1352, 3);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1362, 3);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1363, 3);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1416, 3);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1461, 3);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1499, 3);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1501, 3);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1502, 3);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1504, 3);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1542, 3);
INSERT IGNORE INTO mods_buffer_content VALUES (2, 1036, 3);
INSERT IGNORE INTO mods_buffer_content VALUES (2, 1062, 3);
INSERT IGNORE INTO mods_buffer_content VALUES (2, 1086, 3);
INSERT IGNORE INTO mods_buffer_content VALUES (3, 1044, 3);
INSERT IGNORE INTO mods_buffer_content VALUES (3, 1240, 3);
INSERT IGNORE INTO mods_buffer_content VALUES (3, 1388, 3);
INSERT IGNORE INTO mods_buffer_content VALUES (3, 1397, 3);
INSERT IGNORE INTO mods_buffer_content VALUES (4, 1035, 3);
INSERT IGNORE INTO mods_buffer_content VALUES (4, 1259, 3);
INSERT IGNORE INTO mods_buffer_content VALUES (4, 1268, 3);
INSERT IGNORE INTO mods_buffer_content VALUES (13, 4700, 3);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 264, 4);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 265, 4);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 267, 4);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 268, 4);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 269, 4);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 271, 4);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 272, 4);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 274, 4);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 275, 4);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 304, 4);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 349, 4);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 364, 4);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 764, 4);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 828, 4);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1323, 4);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1352, 4);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1362, 4);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1363, 4);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1416, 4);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1461, 4);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1499, 4);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1501, 4);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1502, 4);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1504, 4);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1542, 4);
INSERT IGNORE INTO mods_buffer_content VALUES (2, 1036, 4);
INSERT IGNORE INTO mods_buffer_content VALUES (2, 1086, 4);
INSERT IGNORE INTO mods_buffer_content VALUES (3, 1044, 4);
INSERT IGNORE INTO mods_buffer_content VALUES (3, 1240, 4);
INSERT IGNORE INTO mods_buffer_content VALUES (3, 1388, 4);
INSERT IGNORE INTO mods_buffer_content VALUES (3, 1397, 4);
INSERT IGNORE INTO mods_buffer_content VALUES (4, 1035, 4);
INSERT IGNORE INTO mods_buffer_content VALUES (4, 1259, 4);
INSERT IGNORE INTO mods_buffer_content VALUES (4, 1268, 4);
INSERT IGNORE INTO mods_buffer_content VALUES (6, 1243, 4);
INSERT IGNORE INTO mods_buffer_content VALUES (13, 4703, 4);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 264, 5);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 265, 5);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 267, 5);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 268, 5);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 273, 5);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 276, 5);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 304, 5);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 349, 5);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 363, 5);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 364, 5);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 365, 5);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 764, 5);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 830, 5);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1323, 5);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1352, 5);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1362, 5);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1413, 5);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1416, 5);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1461, 5);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1500, 5);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1501, 5);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1503, 5);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1504, 5);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1542, 5);
INSERT IGNORE INTO mods_buffer_content VALUES (2, 1036, 5);
INSERT IGNORE INTO mods_buffer_content VALUES (2, 1062, 5);
INSERT IGNORE INTO mods_buffer_content VALUES (2, 1303, 5);
INSERT IGNORE INTO mods_buffer_content VALUES (3, 1044, 5);
INSERT IGNORE INTO mods_buffer_content VALUES (3, 1085, 5);
INSERT IGNORE INTO mods_buffer_content VALUES (3, 1389, 5);
INSERT IGNORE INTO mods_buffer_content VALUES (3, 1397, 5);
INSERT IGNORE INTO mods_buffer_content VALUES (4, 1035, 5);
INSERT IGNORE INTO mods_buffer_content VALUES (4, 1259, 5);
INSERT IGNORE INTO mods_buffer_content VALUES (6, 1078, 5);
INSERT IGNORE INTO mods_buffer_content VALUES (13, 4702, 5);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 264, 6);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 265, 6);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 267, 6);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 268, 6);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 273, 6);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 276, 6);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 304, 6);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 349, 6);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 363, 6);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 364, 6);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 365, 6);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 764, 6);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1323, 6);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1352, 6);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1362, 6);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1413, 6);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1416, 6);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1461, 6);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1500, 6);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1501, 6);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1503, 6);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1504, 6);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1542, 6);
INSERT IGNORE INTO mods_buffer_content VALUES (2, 1036, 6);
INSERT IGNORE INTO mods_buffer_content VALUES (2, 1062, 6);
INSERT IGNORE INTO mods_buffer_content VALUES (2, 1303, 6);
INSERT IGNORE INTO mods_buffer_content VALUES (3, 1044, 6);
INSERT IGNORE INTO mods_buffer_content VALUES (3, 1059, 6);
INSERT IGNORE INTO mods_buffer_content VALUES (3, 1085, 6);
INSERT IGNORE INTO mods_buffer_content VALUES (3, 1304, 6);
INSERT IGNORE INTO mods_buffer_content VALUES (3, 1389, 6);
INSERT IGNORE INTO mods_buffer_content VALUES (3, 1397, 6);
INSERT IGNORE INTO mods_buffer_content VALUES (4, 1035, 6);
INSERT IGNORE INTO mods_buffer_content VALUES (4, 1259, 6);
INSERT IGNORE INTO mods_buffer_content VALUES (6, 1078, 6);
INSERT IGNORE INTO mods_buffer_content VALUES (4, 1035, 7);
INSERT IGNORE INTO mods_buffer_content VALUES (13, 4699, 7);
INSERT IGNORE INTO mods_buffer_content VALUES (3, 1388, 7);
INSERT IGNORE INTO mods_buffer_content VALUES (4, 1259, 7);
INSERT IGNORE INTO mods_buffer_content VALUES (3, 1393, 7);
INSERT IGNORE INTO mods_buffer_content VALUES (3, 1392, 7);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1504, 7);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1499, 7);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1501, 7);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1502, 7);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1363, 7);
INSERT IGNORE INTO mods_buffer_content VALUES (3, 1284, 7);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1519, 7);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1353, 7);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1352, 7);
INSERT IGNORE INTO mods_buffer_content VALUES (3, 1240, 7);
INSERT IGNORE INTO mods_buffer_content VALUES (3, 1191, 7);
INSERT IGNORE INTO mods_buffer_content VALUES (3, 1182, 7);
INSERT IGNORE INTO mods_buffer_content VALUES (3, 1189, 7);
INSERT IGNORE INTO mods_buffer_content VALUES (2, 1062, 7);
INSERT IGNORE INTO mods_buffer_content VALUES (2, 1036, 7);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 274, 7);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 275, 7);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 271, 7);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 272, 7);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 915, 7);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 310, 7);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 529, 7);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 304, 7);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 268, 7);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 269, 7);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 264, 7);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 267, 7);
INSERT IGNORE INTO mods_buffer_content VALUES (4, 1035, 8);
INSERT IGNORE INTO mods_buffer_content VALUES (13, 4699, 8);
INSERT IGNORE INTO mods_buffer_content VALUES (3, 1389, 8);
INSERT IGNORE INTO mods_buffer_content VALUES (4, 1259, 8);
INSERT IGNORE INTO mods_buffer_content VALUES (3, 1393, 8);
INSERT IGNORE INTO mods_buffer_content VALUES (3, 1392, 8);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1504, 8);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1499, 8);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1501, 8);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1502, 8);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1363, 8);
INSERT IGNORE INTO mods_buffer_content VALUES (3, 1284, 8);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1519, 8);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1353, 8);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1352, 8);
INSERT IGNORE INTO mods_buffer_content VALUES (3, 1240, 8);
INSERT IGNORE INTO mods_buffer_content VALUES (3, 1191, 8);
INSERT IGNORE INTO mods_buffer_content VALUES (3, 1182, 8);
INSERT IGNORE INTO mods_buffer_content VALUES (3, 1189, 8);
INSERT IGNORE INTO mods_buffer_content VALUES (2, 1036, 8);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 274, 8);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 275, 8);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 271, 8);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 272, 8);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 310, 8);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 530, 8);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 529, 8);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 304, 8);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 268, 8);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 269, 8);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 264, 8);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 267, 8);
INSERT IGNORE INTO mods_buffer_content VALUES (4, 1035, 9);
INSERT IGNORE INTO mods_buffer_content VALUES (13, 4703, 9);
INSERT IGNORE INTO mods_buffer_content VALUES (3, 1389, 9);
INSERT IGNORE INTO mods_buffer_content VALUES (4, 1259, 9);
INSERT IGNORE INTO mods_buffer_content VALUES (3, 1393, 9);
INSERT IGNORE INTO mods_buffer_content VALUES (3, 1392, 9);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1504, 9);
INSERT IGNORE INTO mods_buffer_content VALUES (3, 1040, 9);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1500, 9);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1501, 9);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1363, 9);
INSERT IGNORE INTO mods_buffer_content VALUES (3, 1284, 9);
INSERT IGNORE INTO mods_buffer_content VALUES (3, 1085, 9);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1353, 9);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 1352, 9);
INSERT IGNORE INTO mods_buffer_content VALUES (2, 1303, 9);
INSERT IGNORE INTO mods_buffer_content VALUES (3, 1191, 9);
INSERT IGNORE INTO mods_buffer_content VALUES (3, 1182, 9);
INSERT IGNORE INTO mods_buffer_content VALUES (3, 1189, 9);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 365, 9);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 276, 9);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 273, 9);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 530, 9);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 529, 9);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 304, 9);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 268, 9);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 269, 9);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 264, 9);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 267, 9);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 305, 9);
INSERT IGNORE INTO mods_buffer_content VALUES (1, 349, 9);
